# Generated by Django 4.1.3 on 2022-11-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('bestbefore', models.DateTimeField()),
                ('datamanufacture', models.DateTimeField()),
                ('dataarrival', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('types', models.CharField(max_length=20)),
                ('qr_code', models.CharField(default=None, max_length=100)),
                ('discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=60)),
                ('image_url', models.CharField(max_length=250)),
                ('location_lang', models.CharField(max_length=250)),
                ('location_lat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tg_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=250)),
                ('location_lang', models.CharField(max_length=250)),
                ('location_lat', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('types', models.CharField(max_length=20)),
                ('archive', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.users')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.stores')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.stores'),
        ),
    ]
